In [1]:
#Bài 1
import numpy as np
a = np.array([1, 2, 3]) #Khởi tại mảng gồm 3 phần tử và gán vào biến a
print(type(a)) #In ra kiểu dữ liệu của mảng a
print(a.shape) #In ra dạng shape(hình dạng) của a, mảng a có 3 phần tử trong 1 chiều nên kết quả sẽ là (3,)
print(a[0], a[1], a[2]) #In ra các phần tử trong mảng a theo thứ tự 0, 1, 2
a[0] = 5 #Đặt giá trị cho phần tử đầu tiên trong mảng a có giá trị là 5
print(a) #In ra mảng a
b = np.array([[1,2,3],[4,5,6]]) #khởi tạo 1 mảng 2 chiều(ma trận) và đặt tên cho nó là b
print(b.shape) #in ra shape(hình dạng) của b có 2 hàng và 3 cột (2,3)
print(b[0, 0], b[0, 1], b[1, 0]) #In ra các phần tử tại vị trí, hàng 0 cột 0 là 1, hàng 0 cột 1 là 2, hàng 1 cột 0 là 4

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [3]:
#Bài 2
import numpy as np
a = np.zeros((2,2)) #Khởi tạo mảng 2 hàng 2 cột với các phần tử là toàn chữ số 0 và gán vào biến a
b = np.ones((1,2)) #Khởi tạo mảng với 1 hàng và 2 cột với giá trị của tất cả các phần tử là 1 và đặt tên là b
c = np.full((2,2), 7) #Khởi tạo mảng 2x2 với tất cả các phần tử đều là 7
d = np.eye(2) #Khởi tạo mảng 2x2 với tất cả các phần tử của đường chéo chính là 1 và các phần tử còn lại là 0
e = np.random.random((2,2)) #Khởi tạo một mảng 2x2 với các giá trị ngẫu nhiên trong khoảng [0, 1]

In [4]:
#Bài 3
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) #Khởi tạo một mảng 3x4 và gắn vào biến a
b = a[:2, 1:3]
print(a[0, 1]) #In ra phần tử ở hàng 0 cột 1 của a với giá trị là 2
b[0, 0] = 77 #Gán phần tử ở hàng 0 cột 0 của mảng b bằng 77
print(a[0, 1]) #In ra phần tử ở hàng 0 cột 1 của mảng a với giá trị là 77

2
77


In [5]:
#Bài 4
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) #Khởi tạo mảng 3x4 lấy tên là a
row_r1 = a[1, :] #lấy hàng thứ 2 và gán với biến row_r1 
row_r2 = a[1:2, :] #Lấy tất cả phần tử ở hàng 2
print(row_r1, row_r1.shape) #In ra các phần tử của row_r1 và hình dạng của row_r1 là (4,). Nó là mảng có 4 phần tử và chỉ có 1 chiều (là một vector).
print(row_r2, row_r2.shape) #In ra các phần tử ở row_r2 và in là hình dạng của nó là (1,4) là mảng 2 chiều 
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape) #In ra col_r1 và hình dạng của nó là (3,). Nó là mảng có 3 phần tử và chỉ có 1 chiều.
print(col_r2, col_r2.shape) #In ra col_r2 và hình dạng của nó là (3,1)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [6]:
#Bài 5
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]]) #Khởi tạo mảng có kích thước 3x2
print(a[[0, 1, 2], [0, 1, 0]]) #Lấy các phần tử tại các cặp tọa độ (0, 0), (1, 1), và (2, 0)
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) #Lấy các phần tử riêng lẻ tại cùng các tọa độ trên, sau đó tạo mảng từ chúng
print(a[[0, 0], [1, 1]]) #Lấy các phần tử tại các cặp tọa độ (0, 1) và (0, 1) (lặp lại)
print(np.array([a[0, 1], a[0, 1]])) #Lấy phần tử tại tọa độ (0, 1) (giá trị 2) và tạo mảng chứa giá trị đó hai lần.

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [7]:
#Bài 6
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) #Khởi tạo mảng có kích thước 4x3 và gán nó bằng biến a
print(a) #In ra các phần tử trong mảng a
b = np.array([0, 2, 0, 1]) #Khởi tạo mảng gồm 1 hàng có kích thước 1x4 và gán nó bằng biến b
print(a[np.arange(4), b]) #tạo mảng chỉ số hàng: [0, 1, 2, 3]. Lấy các phần tử tại các cặp tọa độ (0, 0), (1, 2), (2, 0), (3, 1)
a[np.arange(4), b] += 10 #Cộng 10 vào những phàn tử được chọn ở bước trên
print(a) #In ra mảng a sau khi cập nhật.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [8]:
#Bài 7
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2) #Tạo ra một mảng các phần tử của mảng a và so sánh với 2 trả về giá trị kiểu boolean True hoặc False
print(bool_idx) #In ra mảng boolean đó
print(a[bool_idx]) #Sử dụng mảng Boolean để chọn các phần tử trong a tại những vị trí có giá trị True
print(a[a > 2]) #Thực hiện cùng phép so sánh và lọc chỉ trong một bước. Kết quả là mảng 1D giống hệt bước trên.


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [9]:
#Bài 8
import numpy as np
x = np.array([1, 2]) #Khởi tạo mảng có kích thước là 1x2 và gán nó vào biến x
print(x.dtype) #In ra kiểu dữ liệu của mảng x và nó sẽ là kiểu int
x = np.array([1.0, 2.0]) #Tại mảng chứa số thực có kích thước 1x2 và gán vào biến x
print(x.dtype) #In ra kiểu dữ liệu của mảng x và nó sẽ là kiểu float
x = np.array([1, 2], dtype=np.int64) #Tạo mảng chứa các số nguyên và chỉ định rõ ràng kiểu dữ liệu 
print(x.dtype) #In ra kiểu dữ liệu của mảng x và nó sẽ là int64

int64
float64
int64


In [11]:
#Bài 9
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64) #Khởi tạo mảng có kích thước 2x2 và gán nó là biến x
y = np.array([[5,6],[7,8]], dtype=np.float64) #Khởi tạo mảng có kích thước 2x2 và gán nó là biến y
print(x + y) #In ra kết quả của 2 mảng cộng lại
print(np.add(x, y)) #In ra mảng x thêm vào với y, kết quả như cộng 2 mảng ở trên
print(x - y) #In ra kết quả của mảng x trừ đi y
print(np.subtract(x, y)) #In ra mảng x trừ đi y giống phép trừ
print(x * y) #In ra kết quả nhân 2 mảng 
print(np.multiply(x, y)) #In ra kết quả nhân 2 mảng nhưng dùng hàm multipply
print(x / y) #In ra kết quả chia 2 mảng 
print(np.divide(x, y)) #In ra kết quả chia 2 mảng nhưng dùng hàm
print(np.sqrt(x)) #In ra kết quả lấy căn bậc 2 của 2 mảng

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [12]:
#Bài 10
import numpy as np
x = np.array([[1,2],[3,4]]) #Khởi tạo mảng có kích thước 2x2 và gán nó là biến x
y = np.array([[5,6],[7,8]]) #Khởi tạo mảng có kích thước 2x2 và gán nó là biến y
v = np.array([9,10]) #Khởi tạo mảng có kích thước 1x2 và gán nó là biến v
w = np.array([11, 12]) #Khởi tạo mảng có kích thước 1x2 và gán nó là biến w
print(v.dot(w)) #Lấy tích vô hướng của v với w và in ra kết quả
print(np.dot(v, w)) #Lấy tích vô hướng của v với w và in ra kết quả tương đương với cách trên
print(x.dot(v)) #Lấy tích vô hướng của x với v và in ra kết quả
print(np.dot(x, v)) #Lấy tích vô hướng của x với v và in ra kết quả tương đương với cách trên
print(x.dot(y)) #Lấy tích vô hướng của x với y và in ra kết quả
print(np.dot(x, y)) #Lấy tích vô hướng của x với y và in ra kết quả tương đương với cách trên

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
#Bài 11
import numpy as np
x = np.array([[1,2],[3,4]]) #Khởi tạo mảng có kích thước 2x2 và gán nó là biến x
print(np.sum(x)) #Tính tổng của tất cả các phần tử trong mảng x
print(np.sum(x, axis=0)) #Tính tổng các phần tử của x theo cột 
print(np.sum(x, axis=1)) #Tính tổng các phần tử của x theo hàng
x = np.array([[1,2], [3,4]])
print(x) #In ra mảng x có kích thước 2x2
print(x.T) #Lấy chuyển vị của $x$ (đổi hàng thành cột).
v = np.array([1,2,3])
print(v) #In ra mảng v có kích thước 1x3
print(v.T) #Lấy chuyển vị của v nhưng không bị thay đổi do v là mảng 1D

10
[4 6]
[3 7]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [18]:
#Bài 12
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) #Tạo một mảng mới y có cùng hình dạng và kiểu dữ liệu với x, nhưng chưa được khởi tạo (chứa các giá trị rác)
for i in range(4):
    y[i, :] = x[i, :] + v
print(y) #In ra mảng y sau khi tất cả các phép toán đã được thực hiện cộng vector từng phần tử

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [20]:
#Bài 13
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1)) #Sử dụng np.tile để lặp lại vector 1D v (4 lần theo chiều dọc/hàng, 1 lần theo chiều ngang/cột). Kết quả là một ma trận 4x3 (vv) có cùng hình dạng với x
print(vv) #In ra ma trận vv đã được lặp lại
y = x + vv #Cộng hai ma trận x và vv có cùng hình dạng (4x3) với nhau
print(y) #In ra mảng y sau phép cộng

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [21]:
#Bài 14
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v #Nó tự động sao chép vector v theo chiều dọc/hàng (axis 0) 4 lần, sau đó cộng từng phần tử với x
print(y) #In ra mảng y sau phép cộng

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [23]:
#Bài 15
import numpy as np
v = np.array([1,2,3]) # v has shape (3,)
w = np.array([4,5]) # w has shape (2,)
print(np.reshape(v, (3, 1)) * w) #Phép nhân cộ của v với hàng của w, v được định hình lại thành vector cột (3x1), Nó là phép nhân một ma trận 3x2
x = np.array([[1,2,3], [4,5,6]]) #Khởi tạo mảng có kích thước 3x3 và gán nó là biến x
print(x + v) #Cộng 2 mảng x với v, 2 mảng khác kích thước kết quả sẽ là một mảng có kích thước như mảng x
print((x.T + w).T)#Cộng hai vector cột gián tiếp, với chuyển vị (3x2) của mảng x, kết quả được chuyển vị trở lại hình dạng 2x3
print(x + np.reshape(w, (2, 1)))#Cộng x với vecto cột, vector w được định hình lại thành vector cột (2x1)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [24]:
#Bài 16
import numpy as np
v = np.array([1,2,3]) #Khởi tạo mảng có kích thước 1x3 và gán nó là biến v
w = np.array([4,5]) #Khởi tạo mảng có kích thước 1x2 và gán nó là biến w
print(np.reshape(v, (3, 1)) * w) #In ra kéo dài vector cột v (3x1) và vector hàng w (1x2) để tạo ra một ma trận 3x2
x = np.array([[1,2,3], [4,5,6]]) #Khởi tạo mảng có kích thước 3x3 và gán nó là biến x
print(x + v) #In ra kết quả của phép cộng hai mảng
print((x.T + w).T) #In ra cộng w vào ma trận chuyển vị x, sau đó chuyển vị lại
print(x + np.reshape(w, (2, 1))) #In ra vector w được định hình lại thành vector cột (2x1), sau đó được kéo dài theo chiều ngang 3 lần, cộng vào mỗi cột của x
print(x * 2) #Nhân vô hướng ma trận x với 2

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
